FROM python:3.11-slim

WORKDIR /admin_django
COPY ./infra/requirements_admin_django.txt ./requirements.txt
RUN pip3 install -r ./requirements.txt --no-cache-dir
COPY ./src/admindjango_bot ./

CMD ["gunicorn", "admindjango_bot.wsgi:application", "--bind", "0:8000"]
