version: '3.8'

services:

  db:
    image: postgres:16.0-alpine
    volumes:
      - db_volume:/var/lib/postgresql/data/
    env_file:
      - ../.env

  vtordish:
    container_name: vtordish
    build:
      context: ../
      dockerfile: ./infra/Dockerfile
    depends_on:
      - db
    env_file:
      - ../.env

volumes:
  db_volume:
