version: '3.8'

services:
  db:
    image: postgres:16.0-alpine
    container_name: vtordish_db
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
  vtordish:
    container_name: vtordish
    depends_on:
      - db
    build:
      context: ../
      dockerfile: ./infra/Dockerfile
    env_file:
      - ../.env

volumes:
  db_value: