MENU_ABOUT_FOND = 'О фонде'
MENU_ONBOARDING = 'Онбординг'
MENU_GENERAL_INFO = 'Основная информация'
MENU_GENERAL_RULES = 'Общие правила'
MENU_KNOWLEDGE_BASE = 'База знаний'
MENU_FEEDBACK = 'Обратная связь'
MENU_REGLAMENTS_AND_FORMS = 'Регламенты и формы'
MENU_FAQ = 'FAQ'
MENU_CONTACT_LIST = 'Список контактов'
BACK_BUTTON = 'Назад'

