CHECK: int = 1
MENU: int = 2
ABOUT_FUND_MENU_STATE: int = 60
FUND_MISSION_STATE: int = 601
THINGS_PATH_STATE: int = 602
PROCESSES_ANATOMY_STATE: int = 603
FUND_PROJECTS_STATE: int = 604
ANNUAL_REPORTS_STATE: int = 605
