# Generated by Django 4.2.7 on 2023-11-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFundKeyboards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyboard_name', models.CharField(max_length=100)),
                ('keyboard_text', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'about_fund_keyboards',
            },
        ),
    ]
