# Generated by Django 4.2.7 on 2023-11-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfoKeyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyboard_text', models.CharField(max_length=100, verbose_name='Текст внутри кнопки')),
                ('keyboard_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'basic_info_keyboards',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutfundkeyboard',
            options={'verbose_name_plural': 'Модуль с реализацией клавиатур для блока "О Фонде"'},
        ),
        migrations.AlterField(
            model_name='aboutfundkeyboard',
            name='keyboard_text',
            field=models.CharField(max_length=100, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='keyboard_text',
            field=models.CharField(max_length=100, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='onboardingkeyboard',
            name='keyboard_text',
            field=models.CharField(max_length=100, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='ruleskeyboard',
            name='keyboard_text',
            field=models.CharField(max_length=100, verbose_name='Текст внутри кнопки'),
        ),
    ]
