# Generated by Django 4.2.7 on 2023-11-27 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('admin_bot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QueryPatterns',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.AlterModelOptions(
            name='aboutfundtext',
            options={'verbose_name_plural': 'Тексты для подраздела "О Фонде"'},
        ),
        migrations.AlterModelOptions(
            name='basicinfotext',
            options={
                'verbose_name_plural': (
                    'Тексты для ',
                    'подраздела "Основная иннформация"',
                )
            },
        ),
        migrations.AlterModelOptions(
            name='button',
            options={'verbose_name_plural': 'Названия кнопок меню'},
        ),
        migrations.AlterModelOptions(
            name='contactlisttext',
            options={
                'verbose_name_plural': (
                    'Тексты для ',
                    'подраздела "Список контактов"',
                )
            },
        ),
        migrations.AlterModelOptions(
            name='faqtext',
            options={'verbose_name_plural': 'Тексты для подраздела "FAQ"'},
        ),
        migrations.AlterModelOptions(
            name='links',
            options={
                'verbose_name_plural': (
                    'Ссылки для подраздела ',
                    '"Обратнаня связь" и "База знаний"',
                )
            },
        ),
        migrations.AlterModelOptions(
            name='onboardingtext',
            options={
                'verbose_name_plural': 'Тексты для подраздела "Онбоардинг"'
            },
        ),
        migrations.AlterModelOptions(
            name='regformstext',
            options={
                'verbose_name_plural': (
                    'Тексты для ',
                    'подраздела "Регламенннты и формы"',
                )
            },
        ),
        migrations.AlterModelOptions(
            name='rulestext',
            options={
                'verbose_name_plural': 'Тексты для подраздела "Общие правила"'
            },
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name_plural': 'Базовые сообщения бота'},
        ),
    ]
