# Generated by Django 4.2.7 on 2023-11-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_bot', '0002_delete_querypatterns_delete_state_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicinfotext',
            options={'verbose_name_plural': 'Тексты для подраздела "Основная информация"'},
        ),
        migrations.AlterModelOptions(
            name='regformstext',
            options={'verbose_name_plural': 'Тексты для подраздела "Регламенты и формы"'},
        ),
    ]
