# Generated by Django 4.2.7 on 2023-11-09 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_bot', '0002_basicinfokeyboard_alter_aboutfundkeyboard_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicinfokeyboard',
            options={'verbose_name_plural': 'Базовые информационные кнопки'},
        ),
        migrations.AlterModelOptions(
            name='keyboard',
            options={'verbose_name_plural': 'Гл.Меню и FAQ кнопки'},
        ),
        migrations.AlterModelOptions(
            name='onboardingkeyboard',
            options={'verbose_name_plural': 'Онбординг кнопки'},
        ),
        migrations.AlterModelOptions(
            name='ruleskeyboard',
            options={'verbose_name_plural': 'Клавиатура для подраздела "Общие правила"'},
        ),
    ]
