# Generated by Django 4.2.7 on 2023-11-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin_bot', '0003_alter_basicinfotext_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactListKeyboard',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'constant_description',
                    models.CharField(
                        max_length=1600, null=True, verbose_name='Описание'
                    ),
                ),
                (
                    'constant_text',
                    models.CharField(
                        max_length=1600, verbose_name='Текст внутри кнопки'
                    ),
                ),
                ('constant_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Клавиатуры раздела "Список контактов"',
                'db_table': 'contact_list_keyboards',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutfundkeyboard',
            options={'verbose_name_plural': 'Клавиатуры раздела "О Фонде"'},
        ),
        migrations.AlterModelOptions(
            name='aboutfundtext',
            options={'verbose_name_plural': 'Тексты раздела "О Фонде"'},
        ),
        migrations.AlterModelOptions(
            name='basicinfokeyboard',
            options={
                'verbose_name_plural': (
                    'Клавиатуры раздела ',
                    '"Основная информация"',
                )
            },
        ),
        migrations.AlterModelOptions(
            name='basicinfotext',
            options={
                'verbose_name_plural': 'Тексты раздела "Основная информация"'
            },
        ),
        migrations.AlterModelOptions(
            name='contactlisttext',
            options={
                'verbose_name_plural': 'Тексты раздела "Список контактов"'
            },
        ),
        migrations.AlterModelOptions(
            name='faqtext',
            options={'verbose_name_plural': 'Тексты раздела "FAQ"'},
        ),
        migrations.AlterModelOptions(
            name='keyboard',
            options={
                'verbose_name_plural': (
                    'Клавиатуры основного ',
                    'меню и раздела "FAQ"',
                )
            },
        ),
        migrations.AlterModelOptions(
            name='links',
            options={
                'verbose_name_plural': (
                    'Ссылки для подраздела ',
                    '"Обратнаня связь" и "База знаний"',
                )
            },
        ),
        migrations.AlterModelOptions(
            name='onboardingkeyboard',
            options={'verbose_name_plural': 'Клавиатуры раздела "Онбординг"'},
        ),
        migrations.AlterModelOptions(
            name='onboardingtext',
            options={'verbose_name_plural': 'Тексты раздела "Онбоардинг"'},
        ),
        migrations.AlterModelOptions(
            name='regformstext',
            options={
                'verbose_name_plural': 'Тексты раздела "Регламенты и формы"'
            },
        ),
        migrations.AlterModelOptions(
            name='ruleskeyboard',
            options={
                'verbose_name_plural': 'Клавиатуры раздела "Общие правила"'
            },
        ),
        migrations.AlterModelOptions(
            name='rulestext',
            options={'verbose_name_plural': 'Тексты раздела "Общие правила"'},
        ),
    ]
