# Generated by Django 4.2.7 on 2023-11-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_bot', '0003_alter_basicinfokeyboard_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutfundkeyboard',
            old_name='keyboard_name',
            new_name='constant_name',
        ),
        migrations.RenameField(
            model_name='aboutfundkeyboard',
            old_name='keyboard_text',
            new_name='constant_text',
        ),
        migrations.RenameField(
            model_name='basicinfokeyboard',
            old_name='keyboard_name',
            new_name='constant_name',
        ),
        migrations.RenameField(
            model_name='basicinfokeyboard',
            old_name='keyboard_text',
            new_name='constant_text',
        ),
        migrations.RenameField(
            model_name='keyboard',
            old_name='keyboard_name',
            new_name='constant_name',
        ),
        migrations.RenameField(
            model_name='keyboard',
            old_name='keyboard_text',
            new_name='constant_text',
        ),
        migrations.RenameField(
            model_name='onboardingkeyboard',
            old_name='keyboard_name',
            new_name='constant_name',
        ),
        migrations.RenameField(
            model_name='onboardingkeyboard',
            old_name='keyboard_text',
            new_name='constant_text',
        ),
        migrations.RenameField(
            model_name='ruleskeyboard',
            old_name='keyboard_name',
            new_name='constant_name',
        ),
        migrations.RenameField(
            model_name='ruleskeyboard',
            old_name='keyboard_text',
            new_name='constant_text',
        ),
        migrations.AlterField(
            model_name='aboutfundtext',
            name='constant_text',
            field=models.CharField(max_length=100, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='basicinfotext',
            name='constant_text',
            field=models.CharField(max_length=100, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='button',
            name='constant_text',
            field=models.CharField(max_length=100, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='contactlisttext',
            name='constant_text',
            field=models.CharField(max_length=100, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='faqtext',
            name='constant_text',
            field=models.CharField(max_length=100, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='links',
            name='constant_text',
            field=models.CharField(max_length=100, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='onboardingtext',
            name='constant_text',
            field=models.CharField(max_length=100, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='querypatterns',
            name='constant_text',
            field=models.CharField(max_length=100, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='regformstext',
            name='constant_text',
            field=models.CharField(max_length=100, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='rulestext',
            name='constant_text',
            field=models.CharField(max_length=100, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='state',
            name='constant_text',
            field=models.CharField(max_length=100, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='text',
            name='constant_text',
            field=models.CharField(max_length=100, verbose_name='Текст внутри кнопки'),
        ),
    ]
