# Generated by Django 4.2.7 on 2023-11-30 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            'admin_bot',
            '0004_contactlistkeyboard_alter_aboutfundkeyboard_options_and_more',  # noqa
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicinfokeyboard',
            options={
                'verbose_name_plural': 'Клавиатуры раздела "Основная информация"'  # noqa
            },
        ),
        migrations.AlterModelOptions(
            name='keyboard',
            options={
                'verbose_name_plural': 'Клавиатуры основного меню и раздела "FAQ"'  # noqa
            },
        ),
        migrations.AlterModelOptions(
            name='links',
            options={
                'verbose_name_plural': 'Ссылки для подраздела "Обратнаня связь" и "База знаний"'  # noqa
            },
        ),
    ]
