# Generated by Django 4.2.7 on 2023-11-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_bot', '0005_aboutfundkeyboard_constant_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboard',
            name='constant_text',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Текст внутри кнопки'),
        ),
    ]
