# Generated by Django 4.2.7 on 2023-11-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_bot', '0006_alter_keyboard_constant_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboard',
            name='constant_text',
            field=models.CharField(max_length=100, verbose_name='Текст внутри кнопки'),
        ),
    ]
