# Generated by Django 4.2.7 on 2023-11-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_bot', '0007_alter_keyboard_constant_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutfundkeyboard',
            name='constant_description',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='aboutfundkeyboard',
            name='constant_name',
            field=models.CharField(max_length=1400),
        ),
        migrations.AlterField(
            model_name='aboutfundkeyboard',
            name='constant_text',
            field=models.CharField(max_length=1400, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='aboutfundtext',
            name='constant_description',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='aboutfundtext',
            name='constant_name',
            field=models.CharField(max_length=1400),
        ),
        migrations.AlterField(
            model_name='aboutfundtext',
            name='constant_text',
            field=models.CharField(max_length=1400, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='basicinfokeyboard',
            name='constant_description',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='basicinfokeyboard',
            name='constant_name',
            field=models.CharField(max_length=1400),
        ),
        migrations.AlterField(
            model_name='basicinfokeyboard',
            name='constant_text',
            field=models.CharField(max_length=1400, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='basicinfotext',
            name='constant_description',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='basicinfotext',
            name='constant_name',
            field=models.CharField(max_length=1400),
        ),
        migrations.AlterField(
            model_name='basicinfotext',
            name='constant_text',
            field=models.CharField(max_length=1400, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='button',
            name='constant_description',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='button',
            name='constant_name',
            field=models.CharField(max_length=1400),
        ),
        migrations.AlterField(
            model_name='button',
            name='constant_text',
            field=models.CharField(max_length=1400, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='contactlisttext',
            name='constant_description',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contactlisttext',
            name='constant_name',
            field=models.CharField(max_length=1400),
        ),
        migrations.AlterField(
            model_name='contactlisttext',
            name='constant_text',
            field=models.CharField(max_length=1400, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='faqtext',
            name='constant_description',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='faqtext',
            name='constant_name',
            field=models.CharField(max_length=1400),
        ),
        migrations.AlterField(
            model_name='faqtext',
            name='constant_text',
            field=models.CharField(max_length=1400, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='constant_description',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='constant_name',
            field=models.CharField(max_length=1400),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='constant_text',
            field=models.CharField(max_length=1400, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='links',
            name='constant_description',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='links',
            name='constant_name',
            field=models.CharField(max_length=1400),
        ),
        migrations.AlterField(
            model_name='links',
            name='constant_text',
            field=models.CharField(max_length=1400, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='onboardingkeyboard',
            name='constant_description',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='onboardingkeyboard',
            name='constant_name',
            field=models.CharField(max_length=1400),
        ),
        migrations.AlterField(
            model_name='onboardingkeyboard',
            name='constant_text',
            field=models.CharField(max_length=1400, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='onboardingtext',
            name='constant_description',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='onboardingtext',
            name='constant_name',
            field=models.CharField(max_length=1400),
        ),
        migrations.AlterField(
            model_name='onboardingtext',
            name='constant_text',
            field=models.CharField(max_length=1400, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='querypatterns',
            name='constant_description',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='querypatterns',
            name='constant_name',
            field=models.CharField(max_length=1400),
        ),
        migrations.AlterField(
            model_name='querypatterns',
            name='constant_text',
            field=models.CharField(max_length=1400, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='regformstext',
            name='constant_description',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='regformstext',
            name='constant_name',
            field=models.CharField(max_length=1400),
        ),
        migrations.AlterField(
            model_name='regformstext',
            name='constant_text',
            field=models.CharField(max_length=1400, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='ruleskeyboard',
            name='constant_description',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ruleskeyboard',
            name='constant_name',
            field=models.CharField(max_length=1400),
        ),
        migrations.AlterField(
            model_name='ruleskeyboard',
            name='constant_text',
            field=models.CharField(max_length=1400, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='rulestext',
            name='constant_description',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='rulestext',
            name='constant_name',
            field=models.CharField(max_length=1400),
        ),
        migrations.AlterField(
            model_name='rulestext',
            name='constant_text',
            field=models.CharField(max_length=1400, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='state',
            name='constant_description',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='state',
            name='constant_name',
            field=models.CharField(max_length=1400),
        ),
        migrations.AlterField(
            model_name='state',
            name='constant_text',
            field=models.CharField(max_length=1400, verbose_name='Текст внутри кнопки'),
        ),
        migrations.AlterField(
            model_name='text',
            name='constant_description',
            field=models.CharField(max_length=1400, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='text',
            name='constant_name',
            field=models.CharField(max_length=1400),
        ),
        migrations.AlterField(
            model_name='text',
            name='constant_text',
            field=models.CharField(max_length=1400, verbose_name='Текст внутри кнопки'),
        ),
    ]
