"""Keyword search functionality models creation

Revision ID: b03729674f57
Revises:
Create Date: 2023-11-13 14:27:49.845463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'b03729674f57'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'contact',
        sa.Column('full_name', sa.String(length=255), nullable=False),
        sa.Column('phone', sa.String(length=255), nullable=True),
        sa.Column('telegram', sa.String(length=255), nullable=True),
        sa.Column(
            'email',
            sqlalchemy_utils.types.email.EmailType(length=255),
            nullable=False,
        ),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'department',
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'jobtitle',
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'keyword',
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'contactkeyword',
        sa.Column('contact_id', sa.Integer(), nullable=True),
        sa.Column('keyword_id', sa.Integer(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['contact_id'],
            ['contact.id'],
        ),
        sa.ForeignKeyConstraint(
            ['keyword_id'],
            ['keyword.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'contact_id', 'keyword_id', name='unique_contact_id_keyword_id'
        ),
    )
    op.create_table(
        'departmentjobtitle',
        sa.Column('department_id', sa.Integer(), nullable=True),
        sa.Column('job_title_id', sa.Integer(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['department_id'],
            ['department.id'],
        ),
        sa.ForeignKeyConstraint(
            ['job_title_id'],
            ['jobtitle.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'department_id', 'job_title_id', name='unique_department_job_title'
        ),
    )
    op.create_table(
        'position',
        sa.Column('contact_id', sa.Integer(), nullable=True),
        sa.Column('department_job_title_id', sa.Integer(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['contact_id'],
            ['contact.id'],
        ),
        sa.ForeignKeyConstraint(
            ['department_job_title_id'],
            ['departmentjobtitle.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'contact_id',
            'department_job_title_id',
            name='unique_contact_id_department_job_title_id',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position')
    op.drop_table('departmentjobtitle')
    op.drop_table('contactkeyword')
    op.drop_table('keyword')
    op.drop_table('jobtitle')
    op.drop_table('department')
    op.drop_table('contact')
    # ### end Alembic commands ###
